version: "3.3"

services:
  
  bot:
    networks: ['mynetwork']
    build: ./bot

    volumes:
      - ./bot:/app
      - ./cachned_gems:/gems
      
    depends_on: 
      - postgres-setup

    stdin_open: true
    tty: true
    restart: always

    environment:
      - TG_TOKEN
      - PG_PASS

  postgres:
    image: "postgres"
    networks: ['mynetwork']

    environment:
      POSTGRES_PASSWORD: $PG_PASS

    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432 

    restart: always

    stdin_open: true
    tty: true

  postgres-setup:
    networks: ['mynetwork']
    environment:
      POSTGRES_PASSWORD: $PG_PASS

    build: ./postgres
    depends_on: 
      - postgres
    restart: "no"
  
  rabbitmq:
    networks: ['mynetwork']
    image: 'rabbitmq:management'

    ports:
      - 5672:5672

    volumes:
      - ./rmq:/var/lib/rabbitmq/mnesia/

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 1s
      timeout: 1s
      retries: 10

networks: {
  mynetwork: {}
}

