version: "3.3"

services:
  site:
    networks: ['mynetwork']
    build: ./site

    depends_on:
      postgres:
        condition: service_healthy

    stdin_open: true
    tty: true
    restart: always

  bot:
    networks: ['mynetwork']
    build: ./bot

    volumes:
      - ./bot:/app
      - ./cachned_gems:/gems

    depends_on:
      postgres:
        condition: service_healthy

    stdin_open: true
    tty: true
    restart: always

    environment:
      - TG_TOKEN
      - PG_PASS

  postgres:
    image: "postgres"
    networks: ['mynetwork']

    environment:
      POSTGRES_PASSWORD: $PG_PASS

    volumes:
      - ./shared:/shared
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    restart: always

    stdin_open: true
    tty: true

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 50s
      retries: 3


networks:
  mynetwork:
    external: true
    name: my-network
